= Vim Config
Jordan Williams <jordan@jwillikers.com>
:experimental:
:icons: font
ifdef::env-github[]
:tip-caption: :bulb:
:note-caption: :information_source:
:important-caption: :heavy_exclamation_mark:
:caution-caption: :fire:
:warning-caption: :warning:
endif::[]
:Vim: https://www.vim.org/[Vim]
:just: https://github.com/casey/just[just]

My configuration for {Vim}, the ubiquitous text editor.

== Usage

This repository contains the configuration file for {Vim}.
This file is synchronized using this Git repository.
The following instructions detail how to use and sync this repository.

=== Install

Install these settings with the following instructions.

. Install {just} by following the instructions in the https://github.com/casey/just?tab=readme-ov-file#installation[installation section].

. Clone this repository.
+
[,sh]
----
git clone git@github.com:jwillikers/vim-config.git
----

. Change to the project's directory.
+
[,sh]
----
cd vim-config
----

. Run `just` to symlink the config to the correct location.
+
[,sh]
----
just
----

. Reboot for the packages to be available.
+
[,sh]
----
sudo systemctl reboot
----

== Code of Conduct

Please refer to the project's link:CODE_OF_CONDUCT.adoc[Code of Conduct].

== License

This repository is licensed under the https://www.gnu.org/licenses/gpl-3.0.html[GPLv3].
Please refer to the bundled link:LICENSE.adoc[license].

== Copyright

© 2023-2024 Jordan Williams

== Authors

mailto:{email}[{author}]
